### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by skyk33** [skyk33/furima-29266#11]
# URL
https://furima-29266.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
password: skyk33

# 出品者用のメールアドレスとパスワード
email: kome1@example.com
password: komekome1

# 購入者用のメールアドレスとパスワード
email: kome@example.com
password: komekome0

購入用カードの番号・期限・セキュリティコード
No. : 4242424242424242
期限: 4/24
セキュリティーコード：123

**Comment by oooooooba** [comment]
skyk33さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品詳細機能の確認（商品出品時に登録した情報が見られるようになっている）
→商品出品時に記載した「商品説明」が商品詳細ページに表示されていなかったです

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by skyk33** [comment]
ご確認ありがとうございます。
指摘いただいた箇所について修正いたしました。
ご確認をお願いいたします。

**Comment by oooooooba** [comment]
skyk33さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、完成要件は全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。
・商品削除機能の確認
購入済みの商品を削除しようとするとエラーになる

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。

**Comment by skyk33** [comment]
ありがとうございます！ご指摘いただいた箇所について修正する予定です。
